name: codemedia-api-cicd

env:
  AWS_ACCESS_KEY_ID = ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY = ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_DEFAULT_REGION = ${{secrets.AWS_DEFAULT_REGION}}

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - '.deploy/**'
      - '.github/workflows/**'
      - 'src/*'    
  pull_request:
    branches:
      - master    

jobs:
  test:
    name: api testing with jest
    runs-on: ubuntu-latest
    if: github.ref == 'refs/head/master'
    steps:
      - name: perform checkout
        uses: actions/checkout@v2
      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '16'  
      - run: npm ci
      - run: npm run test    

