name: codemedia-api-cicd

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - '.deploy/**'
      - '.github/workflows/**'
      - 'src/*'    
  pull_request:
    branches:
      - master    

jobs:
  test:
    name: api testing with jest
    runs-on: ubuntu-latest
    steps:
      - name: perform checkout
        uses: actions/checkout@v2
      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '16'  
      - run: npm ci
      - run: npm run test   
     

  build_push_image:
    name: build and push to docker
    runs-on: ubuntu-latest
    environment: codemedia-stage
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}}
      - run: docker build -t courageabam/codemedia .
      - run: docker push courageabam/codemedia


