name: codemedia-api-cicd

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - '.deploy/**'
      - '.github/workflows/**'
      - 'src/*'    
  pull_request:
    branches:
      - master    

jobs:
  test:
    name: api testing with jest
    runs-on: ubuntu-latest
    steps:
      - name: perform checkout
        uses: actions/checkout@v2
      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '16'  
      - run: npm ci
      - run: npm run test    

