name: codemedia-api-cicd
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - '.deploy/**'
      - '.github/workflows/**'
      - 'src/*'    
  pull_request:
    branches:
      - master    

jobs:
  test:
    name: api testing with jest
    runs-on: ubuntu-latest
    steps:
      - name: perform checkout
        uses: actions/checkout@v2
      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '16'  
      - run: npm ci
      - run: npm run test   
     

  build_push_image:
    name: build and push to docker
    runs-on: ubuntu-latest
    environment: codemedia-stage
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}}
      - run: docker build -t courageabam/codemedia .
      - run: docker push courageabam/codemedia


  build_ami:
    name: build packer image
    runs-on: ubuntu-latest
    env:
      PKR_VAR_docker_username: ${{secrets.DOCKER_USERNAME}}
      PKR_VAR_docker_password: ${{secrets.DOCKER_PASSWORD}}
    environment: codemedia-stage
    needs: build_push_image
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: install packer on runner
        run: bash .deploy/scripts/packer-install.sh
      - run: cd .deploy/packer && packer validate image.pkr.hcl
      - run: cd .deploy/packer && packer build image.pkr.hcl 